dist: trusty
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "10"
  - "8"
  - "6"
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: npm release
      node_js: "8" # This *has* to be the "build leader"
      script: skip
      after_success:
        - npm run semantic-release
branches:
  only:
    - master
